### ISSUE TITLE
`asText` needs to do some re-escaping of path segments

### ISSUE THREAD

**Issue by glyph** [python-hyper/hyperlink#4]
```
>>> a = hyperlink.URL.fromText("urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob")
>>> b = hyperlink.URL.fromText(a.asText())
>>> a == b
True
>>> c = hyperlink.URL.fromText(a.asIRI().asText())
>>> c == a
False
>>> c == b
False
```

If there are colons (maybe other characters too) in the path segment of a relative URI, they need to be escaped on output; `.asText()` should never produce a syntactically invalid URI.

**Comment by mahmoud** [comment]
Cool, I'll add a test and get this working. PRs welcome, of course!

**Comment by mahmoud** [comment]
So the relevant part of RFC3986 is:

> If a URI contains an authority component, then the path component
   must either be empty or begin with a slash ("/") character.  If a URI
   does not contain an authority component, then the path cannot begin
   with two slash characters ("//").  In addition, a URI reference
   (Section 4.1) may be a relative-path reference, in which case the
   first path segment cannot contain a colon (":") character.

I can implement the latter half, which would fix this issue, of course. But I think that in order to enforce the first half we'd need to do a lot more verification in `__init__`, which has been pretty sparse on semantic checks like that so far. What do you think?

**Comment by mahmoud** [comment]
While I forgot to mention the issue in the commit message, this is fixed in https://github.com/python-hyper/hyperlink/commit/c5749ec5fb3c7124054aa84abf0f4b026a4101b7, bringing the whole path parsing/emission code path way more up to spec. 

There is still the matter of delimiter handling in `__init__` that is the source of much discussion, and I'll see to it shortly. If I can't find a good fix to that, I can make a release just for this, if you'd like.
