### ISSUE TITLE
to_iri() does not decode stray percents

### ISSUE THREAD

**Issue by agoose77** [python-hyper/hyperlink#65]
[From the specification](https://tools.ietf.org/html/rfc3986#section-2.4), URIs should encode stray percents with %25.

However, when calling to_iri(), these encoded percents are not decoded. 
Is this a bug?

**Comment by mahmoud** [comment]
Ahh, I was distracted by your stray percents comment, now I see the question. Basically in this example:

```python
import hyperlink as hl

>>> hl.parse(u'http://example.com/lol%lmao').normalize().to_iri()
URL.from_text(u'http://example.com/lol%25lmao')
```

The question is: "Why isn't `%25` turned back into a `%`"

The simple answer is that `%` is a reserved character in the path, and reserved characters as a rule are not decoded in parts where they are reserved. Other percent-encoded characters are most definitely decoded with `to_iri()`:

```python
>>> print(hl.parse(u'http://example.com/beyoncé').normalize().to_iri().to_text())
http://example.com/beyoncé
```

Another way of looking at it is that hyperlink should never produce a "stray" percent, even when it's obviously stray (because the characters that follow are not hex).

Does that make sense? Maybe we should add a new doc with "URLs" by example, because I think it's really tricky to learn this next-level encoding any other way.

**Comment by agoose77** [comment]
> Another way of looking at it is that hyperlink should never produce a "stray" percent, even when it's obviously stray (because the characters that follow are not hex).
This makes sense. It did cause problems for me, but it was more a case of needing to use DecodedURL to decode the URI fragment aggressively, so I think we can close this.
